s=[10,20,30,5.8,26,90,'sandeep','priyanka']
print("Printing entire list",s)
print("Length of list ", len(s))
print("Printing from 3rd to 6th",s[-6:-2])
print("Printing from 2nd to 7th",s[1:7])
print("Printing till 5th",s[:5])
print("Printing from 3rd to last",s[2:])
print("Printing with increment of 2",s[0:7:2])
print("Printing with increment of 4",s[0:7:4])
print("Printing with increment of 6",s[0:7:6])
print("Printing with increment of 5 starting from 2nd",s[1:7:5])
print("Printing last element using negative slicing",s[-1:])
print("Printing reverse list using negative slicing ",s[::-1])
print(s[::-2])
